apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
    - name: hello-world
      port: 80
      nodePort: 3000
      targetPort: 80
      protocol: TCP
  selector:
    octopusexport: OctopusExport