apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
    - name: hello-world
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    octopusexport: OctopusExport